import type { Essay, Review, TimelineEvent } from './types';

const paragraph = (text: string) => [
  {
    _type: 'block',
    _key: text.slice(0, 12),
    style: 'normal',
    children: [{ _type: 'span', _key: `${text.slice(0, 8)}-span`, text }],
  },
];

export const fixtureEssays: Essay[] = [
  {
    title: '夜里散步',
    slug: 'night-walk',
    date: new Date('2026-06-02'),
    summary: '一段关于夜晚、步行和把念头放慢的短记。',
    tags: ['日常', '安静'],
    mood: '安静',
    body: paragraph('夜里散步的时候，很多白天没有位置的念头会慢慢浮上来。'),
  },
  {
    title: '小房间',
    slug: 'small-room',
    date: new Date('2026-06-01'),
    summary: '关于私人空间和缓慢整理的一点想法。',
    tags: ['自我', '写作'],
    body: paragraph('一个小房间并不只是空间，也是把自己重新收拢起来的方法。'),
  },
  {
    title: '把声音留住',
    slug: 'hold-the-sound',
    date: new Date('2026-05-28'),
    summary: '有些专辑不是被听完，而是被反复带回某个时刻。',
    tags: ['音乐', '记忆'],
    body: paragraph('声音有时比文字更先抵达某个记忆的位置。'),
  },
];

export const fixtureReviews: Review[] = [
  {
    title: 'After Hours',
    slug: 'album-after-hours',
    category: 'music',
    creator: 'The Weeknd',
    year: 2020,
    date: new Date('2026-06-02'),
    rating: 4.3,
    cover: { src: '/covers/reviews/after-hours.svg', alt: 'After Hours 的风格化封面' },
    summary: '霓虹、疲惫和一点危险的浪漫。',
    tags: ['夜晚', '流行'],
    moments: ['夜里走路'],
    body: paragraph('这张专辑像一条被灯光拖长的夜路。'),
  },
  {
    title: '私人语言',
    slug: 'book-private-language',
    category: 'book',
    creator: '维特根斯坦',
    year: 1953,
    date: new Date('2026-06-01'),
    rating: 4,
    cover: { src: '/covers/reviews/private-language.svg', alt: '私人语言的风格化封面' },
    summary: '有些问题不是为了回答，而是为了把问题本身看清。',
    tags: ['哲学', '语言'],
    moments: [],
    body: [],
  },
  {
    title: '晚春',
    slug: 'film-late-spring',
    category: 'film',
    creator: '小津安二郎',
    year: 1949,
    date: new Date('2026-05-30'),
    rating: 4.5,
    cover: { src: '/covers/reviews/late-spring.svg', alt: '晚春的风格化封面' },
    summary: '克制到几乎透明，却让人很难不被击中。',
    tags: ['日本电影', '安静'],
    moments: [],
    body: paragraph('小津的克制不是冷，而是让情绪自己慢慢显影。'),
  },
  {
    title: 'Blue Train',
    slug: 'album-blue-train',
    category: 'music',
    creator: 'John Coltrane',
    year: 1958,
    date: new Date('2026-05-29'),
    rating: 4.4,
    summary: '像一列夜里经过窗边的车，明亮，却不打扰人。',
    tags: ['爵士', '夜晚'],
    moments: ['整理书桌'],
    body: paragraph('铜管声把夜晚推开一点，留下很清楚的空间。'),
  },
  {
    title: 'Melodrama',
    slug: 'album-melodrama',
    category: 'music',
    creator: 'Lorde',
    year: 2017,
    date: new Date('2026-05-28'),
    rating: 4.4,
    summary: '把派对后的空旷写得很亮，也很疼。',
    tags: ['流行', '青春'],
    moments: ['夜晚回家'],
    body: paragraph('它的明亮不是开心，而是情绪在灯下无处可躲。'),
  },
  {
    title: 'For Emma, Forever Ago',
    slug: 'album-for-emma',
    category: 'music',
    creator: 'Bon Iver',
    year: 2007,
    date: new Date('2026-05-27'),
    rating: 4.1,
    summary: '冷一点的民谣，像把一句话留在木屋里回响。',
    tags: ['民谣', '冬天'],
    moments: ['深夜'],
    body: [],
  },
  {
    title: 'Carrie & Lowell',
    slug: 'album-carrie-lowell',
    category: 'music',
    creator: 'Sufjan Stevens',
    year: 2015,
    date: new Date('2026-05-26'),
    rating: 4.6,
    summary: '轻得几乎透明，但情绪并不稀薄。',
    tags: ['民谣', '私人'],
    moments: ['睡前'],
    body: paragraph('它把声音放得很近，近到像一段没有寄出的信。'),
  },
  {
    title: 'Random Access Memories',
    slug: 'album-random-access-memories',
    category: 'music',
    creator: 'Daft Punk',
    year: 2013,
    date: new Date('2026-05-25'),
    rating: 4.2,
    summary: '复古、光滑，带一点机械温柔的流动感。',
    tags: ['电子', '复古'],
    moments: ['散步'],
    body: [],
  },
  {
    title: 'Moon Safari',
    slug: 'album-moon-safari',
    category: 'music',
    creator: 'Air',
    year: 1998,
    date: new Date('2026-05-24'),
    rating: 4,
    summary: '柔软、轻盈，像旧日午后的一层浅色滤镜。',
    tags: ['电子', '午后'],
    moments: ['发呆'],
    body: [],
  },
  {
    title: 'Pink Moon',
    slug: 'album-pink-moon',
    category: 'music',
    creator: 'Nick Drake',
    year: 1972,
    date: new Date('2026-05-23'),
    rating: 4.5,
    summary: '短小、低声，像一盏灯只照亮桌面的一角。',
    tags: ['民谣', '夜晚'],
    moments: ['下雨'],
    body: paragraph('它几乎没有多余修饰，情绪反而保留得完整。'),
  },
  {
    title: '看不见的城市',
    slug: 'book-invisible-cities',
    category: 'book',
    creator: '伊塔洛·卡尔维诺',
    year: 1972,
    date: new Date('2026-05-29'),
    rating: 4.7,
    summary: '像一组轻盈地图，标注的却是记忆和欲望。',
    tags: ['小说', '想象'],
    moments: ['睡前阅读'],
    body: paragraph('每座城市都像一面小镜子，照见人对地方的投射。'),
  },
  {
    title: '小王子',
    slug: 'book-the-little-prince',
    category: 'book',
    creator: '安托万·德·圣-埃克苏佩里',
    year: 1943,
    date: new Date('2026-05-28'),
    rating: 4.3,
    summary: '童话的外壳很轻，里面却有许多关系的回声。',
    tags: ['童话', '经典'],
    moments: ['重读'],
    body: paragraph('现在再读，会更注意它如何处理告别。'),
  },
  {
    title: '黄昏里的谈话',
    slug: 'book-evening-talks',
    category: 'book',
    creator: '虚构作者',
    year: 2021,
    date: new Date('2026-05-27'),
    rating: 3.9,
    summary: '一些很轻的段落，适合在一天结束时读两页。',
    tags: ['随笔', '日常'],
    moments: ['周末'],
    body: [],
  },
  {
    title: '在地上写字',
    slug: 'book-writing-on-earth',
    category: 'book',
    creator: '虚构作者',
    year: 2019,
    date: new Date('2026-05-26'),
    rating: 4,
    summary: '语言朴素，像有人把观察慢慢放到纸面上。',
    tags: ['散文', '自然'],
    moments: ['午后'],
    body: [],
  },
  {
    title: '孤独的城市',
    slug: 'book-lonely-city',
    category: 'book',
    creator: '奥利维娅·莱恩',
    year: 2016,
    date: new Date('2026-05-25'),
    rating: 4.2,
    summary: '把城市里的孤独写得很具体，也很有温度。',
    tags: ['非虚构', '城市'],
    moments: ['夜读'],
    body: paragraph('它没有急着治愈孤独，而是先认真描述孤独的形状。'),
  },
  {
    title: '慢慢读完的一天',
    slug: 'book-slow-reading-day',
    category: 'book',
    creator: '虚构作者',
    year: 2020,
    date: new Date('2026-05-24'),
    rating: 3.8,
    summary: '适合把阅读速度放慢，不急着得到结论。',
    tags: ['随笔', '阅读'],
    moments: ['咖啡'],
    body: [],
  },
  {
    title: '棋王',
    slug: 'book-king-of-chess',
    category: 'book',
    creator: '阿城',
    year: 1984,
    date: new Date('2026-05-23'),
    rating: 4.4,
    summary: '文字很瘦，气却很足。',
    tags: ['小说', '中文'],
    moments: ['重读'],
    body: paragraph('它的力道藏在很省的句子里。'),
  },
  {
    title: '帕特森',
    slug: 'film-paterson',
    category: 'film',
    creator: '吉姆·贾木许',
    year: 2016,
    date: new Date('2026-05-29'),
    rating: 4.4,
    summary: '一部关于重复生活里细小诗意的电影。',
    tags: ['日常', '诗'],
    moments: ['周末夜晚'],
    body: paragraph('它几乎没有用力推进情节，却让重复有了纹理。'),
  },
  {
    title: '哥伦布',
    slug: 'film-columbus',
    category: 'film',
    creator: '郭共达',
    year: 2017,
    date: new Date('2026-05-28'),
    rating: 4.2,
    summary: '建筑、沉默和人与人之间谨慎靠近的距离。',
    tags: ['建筑', '安静'],
    moments: ['夜晚'],
    body: [],
  },
  {
    title: '杨之后',
    slug: 'film-after-yang',
    category: 'film',
    creator: '郭共达',
    year: 2021,
    date: new Date('2026-05-27'),
    rating: 4.1,
    summary: '科幻被放得很轻，重点落在记忆怎样留下痕迹。',
    tags: ['科幻', '家庭'],
    moments: ['雨天'],
    body: paragraph('动人的部分不是设定，而是被保存下来的微小片段。'),
  },
  {
    title: '完美的日子',
    slug: 'film-perfect-days',
    category: 'film',
    creator: '维姆·文德斯',
    year: 2023,
    date: new Date('2026-05-26'),
    rating: 4.5,
    summary: '日复一日的生活，被拍成一种清澈的秩序。',
    tags: ['日常', '东京'],
    moments: ['早晨'],
    body: [],
  },
  {
    title: '驾驶我的车',
    slug: 'film-drive-my-car',
    category: 'film',
    creator: '滨口龙介',
    year: 2021,
    date: new Date('2026-05-25'),
    rating: 4.6,
    summary: '关于失语、倾听和漫长抵达的一部电影。',
    tags: ['对话', '村上春树'],
    moments: ['长夜'],
    body: paragraph('它的慢不是停滞，而像一段终于面对自己的路程。'),
  },
  {
    title: '小森林',
    slug: 'film-little-forest',
    category: 'film',
    creator: '森淳一',
    year: 2014,
    date: new Date('2026-05-24'),
    rating: 4.1,
    summary: '把吃饭、季节和生活节律拍得很清爽。',
    tags: ['生活', '料理'],
    moments: ['周末'],
    body: [],
  },
  {
    title: 'Her',
    slug: 'film-her',
    category: 'film',
    creator: 'Spike Jonze',
    year: 2013,
    date: new Date('2026-05-23'),
    rating: 4.2,
    summary: '温柔的未来感背后，是很旧的人类孤独。',
    tags: ['科幻', '关系'],
    moments: ['独处'],
    body: paragraph('它说的是技术，也更像是在说人如何投向一个声音。'),
  },
];

export const fixtureTimelineEvents: TimelineEvent[] = [
  {
    title: '开始搭个人网站',
    slug: 'website-begins',
    date: new Date('2026-06-02'),
    summary: '把个人网站从想法推进到设计。',
    tags: ['创作'],
    body: paragraph('这是重新整理表达方式的一个开始。'),
  },
  {
    title: '确定聊天入口',
    slug: 'chat-entrance',
    date: new Date('2026-06-01'),
    summary: '把 AI 聊天作为网站的第一入口。',
    tags: ['AI', '网站'],
    body: paragraph('入口是聊天，也是一种让内容被重新靠近的方式。'),
  },
  {
    title: '整理书影音',
    slug: 'music-archive',
    date: new Date('2026-05-30'),
    summary: '决定把音乐、书籍、影视放在同一个私人索引里。',
    tags: ['书影音'],
    body: paragraph('这些记录不是排名，而是某个时刻被击中的痕迹。'),
  },
];
